openapi: 3.0.0
info:
  title: Cart Service API
  version: 1.0.0
paths:
  /carts/{userId}:
    get:
      summary: Get the current cart for a user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
  /carts/{userId}/products:
    post:
      summary: Add a product to the cart
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
      responses:
        '200':
          description: Product added to cart
    delete:
      summary: Remove a product from the cart
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
        - in: query
          name: productId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product removed from cart
  /carts/{userId}/checkout:
    put:
      summary: Proceed to checkout
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Checkout successful
components:
  schemas:
    Cart:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: integer
              quantity:
                type: integer
