openapi: 3.0.0
info:
  title: Favorite Service API
  version: 1.0.0
paths:
  /favorites/{userId}:
    get:
      summary: Get favorite list for a user
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User's favorite list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Favorite'
  /favorites/{userId}/products:
    post:
      summary: Add a product to the favorite list
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
      responses:
        '200':
          description: Product added to favorite list
    delete:
      summary: Remove a product from the favorite list
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: integer
        - in: query
          name: productId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Product removed from favorite list
components:
  schemas:
    Favorite:
      type: object
      properties:
        id:
          type: integer
        userId:
          type: integer
        products:
          type: array
          items:
            type: object
            properties:
              productId:
                type: integer
              name:
                type: string
              price:
                type: number
                format: float
